// Legacy-Folder/Frontend/HRMS-Frontend/source/src/pages/Attendance/components/TimeInDialog.tsx
import React, { useEffect } from "react";
import {
  Dialog,
  DialogContent,
  DialogActions,
  Button,
  Box,
  IconButton,
} from "@mui/material";
import { useForm, FormProvider } from "react-hook-form";
import * as yup from "yup";
import { yupResolver } from "@hookform/resolvers/yup";
import moment from "moment";
import FormDatePicker from "@/components/FormDatePicker";
import FormTextField from "@/components/FormTextField";
import FormSelectField from "@/components/FormSelectField";
import PageHeader from "@/components/PageHeader/PageHeader";
import { EditDetails, TimeInDialogFormValues, TimeInFormData } from "@/pages/Attendance/types";
import SubmitButton from "@/components/SubmitButton/SubmitButton";
import { Close as CloseIcon } from "@mui/icons-material";



interface TimeInDialogProps {
  open: boolean;
  onClose: () => void;
  getDateStatus: (date: string) => string;
  onSubmit: (data: TimeInFormData) => void;
  isLoading: boolean;
  editDetails: EditDetails;
  filledDates: string[];
}

const shouldDisableCustomDate = (
  date: moment.Moment,
  filledDates: string[]
): boolean => {
  const isFilled = filledDates.some((filled) =>
    date.isSame(moment(filled, "MM/DD/YYYY HH:mm:ss"), "day")
  );
  const isToday = date.isSame(moment(), "day");
  return !(!isFilled || isToday);
};


const TimeInDialog: React.FC<TimeInDialogProps> = (props) => {
  const {
    open,
    onClose,
    getDateStatus,
    onSubmit,
    isLoading,
    editDetails,
    filledDates,
  } = props;

  const validationSchema = yup.object().shape({
    date: yup
      .mixed<moment.Moment>()
      .required("Date is required")
      .test(
        "no-edit-today",
        "You cannot edit for the current date.",
        function (value) {
          const { attendanceId } = this.options.context || {};
          return !(
            attendanceId &&
            value &&
            moment(value).isSame(moment(), "day")
          );
        }
      ),
    startTime: yup.string().when("date", {
      is: (date: moment.Moment) =>
        date && date.isValid() && date.isBefore(moment(), "day"),
      then: (schema) => schema.required("Start time is required"),
      otherwise: (schema) => schema,
    }),
    endTime: yup.string().when("date", {
      is: (date: moment.Moment) =>
        date && date.isValid() && date.isBefore(moment(), "day"),
      then: (schema) =>
        schema
          .required("End time is required")
          .test(
            "end-after-start",
            "End time cannot be before start time.",
            function (value) {
              const { startTime } = this.parent;
              return !startTime || !value || value >= startTime;
            }
          ),
      otherwise: (schema) => schema,
    }),
    location: yup.string().required("Location is required"),
    note: yup.string().trim(),
    reason: yup.string().when("date", {
      is: (date: moment.Moment) =>
        date && date.isValid() && date.isBefore(moment(), "day"),
      then: (schema) =>
        schema
          .required("Please tell us why you're adding a past entry.")
          .trim()
          .min(1, "Reason cannot be empty."),
      otherwise: (schema) => schema,
    }),
  });

  const attendanceId = editDetails.id;


  const methods = useForm<TimeInDialogFormValues>({
    resolver: yupResolver(validationSchema),
    context: { attendanceId },
    defaultValues: {
      date: moment(editDetails.date),
      startTime: editDetails.startTime || "",
      endTime: editDetails.endTime || "",
      location: editDetails.location || "",
      note: editDetails.note || "",
      reason: editDetails.reason || "",
      
    },
  });

  const {
    handleSubmit,
    watch,
    setValue,
    reset,
  } = methods;

  

  const watchDate = watch("date");
  const watchStartTime = watch("startTime");
  const watchEndTime = watch("endTime");

  

  useEffect(() => {
    if (open) {
      reset({
        date: moment(editDetails.date),
        startTime: editDetails.startTime || "",
        endTime: editDetails.endTime || "",
        location: editDetails.location || "",
        note: editDetails.note || "",
        reason: editDetails.reason || "",
      });
    }
  }, [open, editDetails]);
useEffect(() => {
    if (watchStartTime && watchEndTime) {
      const total = getTotalHours(watchStartTime, watchEndTime);
      setValue("totalHours", total);
    }
  }, [watchStartTime, watchEndTime]);
 

  const getTotalHours = (
    startTime: string,
    endTime: string
  ): string => {
    if (!startTime || !endTime) return "00:00";
    const [inH, inM] = startTime.split(":").map(Number);
    const [outH, outM] = endTime.split(":").map(Number);
    let totalMinutes = outH * 60 + outM - (inH * 60 + inM);
    if (totalMinutes < 0) totalMinutes += 24 * 60;
    const hours = Math.floor(totalMinutes / 60).toString().padStart(2, "0");
    const minutes = (totalMinutes % 60).toString().padStart(2, "0");
    return `${hours}:${minutes}`;
  };

  const internalSubmit = (data: TimeInDialogFormValues) => {
    const formData: TimeInFormData = {
      ...data,
      date: data.date.format("YYYY-MM-DD"),
      startTime: data.startTime ?? "",
      endTime: data.endTime ?? "",
      location: data.location,
      note: data.note ?? "",
      reason: data.reason ?? "",
    };
    onSubmit(formData);
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="sm"
      fullWidth
      slotProps={{
        paper: { sx: { minWidth: 500 } },
      }}
    >
      <PageHeader variant="h4" title="Time In" />
      <Box sx={{ position: "absolute", right: 20, top: 8 }}>
        <IconButton
          edge="end"
          color="inherit"
          onClick={onClose}
          aria-label="close"
          style={{ position: "absolute", right: 20, top: 8 }}
        >
          <CloseIcon />
        </IconButton>
      </Box>
      <FormProvider {...methods}>
        <DialogContent>
          <Box
            component="form"
            autoComplete="off"
            onSubmit={handleSubmit(internalSubmit)}
            paddingY="30px"
            gap="30px"
            display="flex"
            flexDirection="column"
          >
            <FormDatePicker
              label="Date"
              name="date"
              value={watchDate || null}
              onChange={(date: unknown) => {
                setValue("date", date as moment.Moment, {
                  shouldDirty: true,
                });
              }}
              minDate={moment("2025-06-03", "YYYY-MM-DD")}
              maxDate={moment()}
              shouldDisableDate={(date: moment.Moment) =>
                shouldDisableCustomDate(date, filledDates)
              }
              required
            />
            {watchDate &&
              moment(watchDate).isValid() &&
              getDateStatus(moment(watchDate).format("YYYY-MM-DD")) === "past" && (
                <Box display="flex" gap={2}>
                  <FormTextField
                    name="startTime"
                    label="Start Time"
                    type="time"
                    fullWidth
                    margin="dense"
                    required
                    InputLabelProps={{ shrink: true }}
                  />
                  <FormTextField
                    name="endTime"
                    label="End Time"
                    type="time"
                    fullWidth
                    margin="dense"
                    required
                    InputLabelProps={{ shrink: true }}
                  />
                  {watchStartTime && watchEndTime && (
                    <FormTextField
                      name="totalHours"
                      label="Total Hours"
                      value={getTotalHours(watchStartTime,watchEndTime)}
                      fullWidth
                      margin="dense"
                      InputProps={{ readOnly: true }}
                    />
                  )}
                </Box>
              )}
            <FormSelectField
              name="location"
              label="Location"
              options={[
                { label: "Jaipur Office", value: "Jaipur Office" },
                { label: "Hyderabad Office", value: "Hyderabad Office" },
                { label: "Pune Office", value: "Pune Office" },
                { label: "Remote", value: "Remote" },
                { label: "On Premises", value: "On Premises" },
                { label: "US", value: "US" },
                { label: "Other", value: "Other" },
              ]}
              required
            />
            {watchDate &&
              moment(watchDate).isValid() &&
              getDateStatus(moment(watchDate).format("YYYY-MM-DD")) === "today" && (
                <FormTextField
                  name="note"
                  label="Note (optional)"
                  fullWidth
                  margin="dense"
                />
              )}
            {watchDate &&
              moment(watchDate).isValid() &&
              getDateStatus(moment(watchDate).format("YYYY-MM-DD")) === "past" && (
                <FormTextField
                  name="reason"
                  label="Reason for past entry"
                  fullWidth
                  required
                  margin="dense"
                />
              )}
            <DialogActions sx={{ justifyContent: "center", gap: 2 }}>
              <Button onClick={onClose}>Cancel</Button>
              <SubmitButton
                type="submit"
                variant="contained"
                loading={isLoading}
              >
                Time In
              </SubmitButton>
            </DialogActions>
          </Box>
        </DialogContent>
      </FormProvider>
    </Dialog>
  );
};

export default TimeInDialog;

// hrms-frontend/src/components/attendance/TimeInDialog.vue
<template>
  <v-dialog
    :model-value="modelValue"
    max-width="500px"
    min-width="500px"
    persistent
    scrollable
    @update:model-value="$emit('update:modelValue', $event)"
  >
    <v-card>
      <!-- Dialog Header matching legacy PageHeader -->
      <div class="dialog-header px-4 py-3">
        <v-row no-gutters align="center" justify="space-between">
          <v-col cols="auto">
            <h4 class="text-h5 dark-color" style="font-weight: 500;">
              Time In
            </h4>
          </v-col>
          <v-col cols="auto">
            <v-btn
              icon="mdi-close"
              variant="text"
              size="small"
              @click="handleClose"
            />
          </v-col>
        </v-row>
      </div>
      
      <v-card-text class="px-4" style="padding-top: 30px; padding-bottom: 30px;">
        <v-form ref="formRef" @submit.prevent="handleSubmit">
          <v-row dense>
            <!-- Date Picker -->
            <v-col cols="12">
              <v-text-field
                v-model="formData.date"
                type="date"
                label="Date*"
                :max="maxDate"
                :min="minDate"
                variant="outlined"
                density="comfortable"
                :error-messages="fieldErrors.date"
                hide-details="auto"
                :disabled="shouldDisableDate(formData.date)"
              />
            </v-col>

            <!-- Start Time & End Time (only for past dates) -->
            <template v-if="isPastDate">
              <v-col cols="12" sm="4">
                <v-text-field
                  v-model="formData.startTime"
                  type="time"
                  label="Start Time*"
                  variant="outlined"
                  density="comfortable"
                  :error-messages="fieldErrors.startTime"
                  hide-details="auto"
                  required
                />
              </v-col>
              
              <v-col cols="12" sm="4">
                <v-text-field
                  v-model="formData.endTime"
                  type="time"
                  label="End Time*"
                  variant="outlined"
                  density="comfortable"
                  :error-messages="fieldErrors.endTime"
                  hide-details="auto"
                  required
                  @update:model-value="validateEndTime"
                />
              </v-col>
              
              <v-col cols="12" sm="4">
                <v-text-field
                  :model-value="calculatedHours"
                  label="Total Hours"
                  variant="outlined"
                  density="comfortable"
                  readonly
                  hide-details="auto"
                />
              </v-col>
            </template>

            <!-- Location -->
            <v-col cols="12">
              <v-select
                v-model="formData.location"
                :items="locationOptions"
                label="Location*"
                variant="outlined"
                density="comfortable"
                :error-messages="fieldErrors.location"
                hide-details="auto"
                required
              />
            </v-col>

            <!-- Note (only for today) -->
            <v-col v-if="isToday" cols="12">
              <v-text-field
                v-model="formData.note"
                label="Note (optional)"
                variant="outlined"
                density="comfortable"
                hide-details="auto"
              />
            </v-col>

            <!-- Reason (only for past dates) -->
            <v-col v-if="isPastDate" cols="12">
              <v-text-field
                v-model="formData.reason"
                label="Reason for past entry*"
                variant="outlined"
                density="comfortable"
                :error-messages="fieldErrors.reason"
                hide-details="auto"
                required
              />
            </v-col>
          </v-row>
        </v-form>
      </v-card-text>
      
      <v-card-actions class="px-6 pb-4 pt-2" style="justify-content: center; gap: 16px;">
        <v-btn variant="text" @click="handleClose" min-width="80">
          Cancel
        </v-btn>
        <v-btn
          color="primary"
          variant="elevated"
          :loading="loading"
          :disabled="loading"
          @click="handleSubmit"
          min-width="80"
        >
          Time In
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup lang="ts">
import { ref, reactive, computed, watch, nextTick } from 'vue'
import { format, differenceInMinutes, parse, isBefore, isToday as checkIsToday, isSameDay } from 'date-fns'
import type { EditData } from '@/composables/useAttendanceDialogs'

interface Props {
  modelValue: boolean
  editData?: EditData | null
  loading: boolean
  filledDates: string[]
}

const props = defineProps<Props>()

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
  submit: [data: any]
}>()

// Refs
const formRef = ref()

// Reactive data
const formData = reactive({
  date: '',
  startTime: '',
  endTime: '',
  location: '',
  note: '',
  reason: ''
})

const fieldErrors = reactive<{
  date: string[]
  startTime: string[]
  endTime: string[]
  location: string[]
  reason: string[]
}>({
  date: [],
  startTime: [],
  endTime: [],
  location: [],
  reason: []
})

// Location options matching legacy exactly
const locationOptions = [
  'Jaipur Office',
  'Hyderabad Office',
  'Pune Office',
  'Remote',
  'On Premises',
  'US',
  'Other'
]

// Computed properties
const today = computed(() => format(new Date(), 'yyyy-MM-dd'))
const maxDate = computed(() => format(new Date(), 'yyyy-MM-dd'))
const minDate = computed(() => '2025-06-03') // Matching legacy min date

const isEdit = computed(() => props.editData && props.editData.id > 0)

const isPastDate = computed(() => {
  if (!formData.date) return false
  const selectedDate = new Date(formData.date)
  const todayDate = new Date()
  return isBefore(selectedDate, todayDate) && !isSameDay(selectedDate, todayDate)
})

const isToday = computed(() => {
  if (!formData.date) return false
  return checkIsToday(new Date(formData.date))
})

const calculatedHours = computed(() => {
  if (formData.startTime && formData.endTime) {
    try {
      const start = parse(formData.startTime, 'HH:mm', new Date())
      const end = parse(formData.endTime, 'HH:mm', new Date())
      let minutes = differenceInMinutes(end, start)
      
      if (minutes < 0) {
        minutes += 24 * 60 // Handle overnight
      }
      
      if (minutes > 0) {
        const hours = Math.floor(minutes / 60)
        const mins = minutes % 60
        return `${hours.toString().padStart(2, '0')}:${mins.toString().padStart(2, '0')}`
      }
    } catch (error) {
      // Invalid time format
    }
  }
  return '00:00'
})

// Methods
const shouldDisableDate = (date: string) => {
  if (!date) return false
  
  const selectedDate = new Date(date)
  const isFilled = props.filledDates.some(filled => 
    isSameDay(new Date(filled), selectedDate)
  )
  const isCurrentToday = checkIsToday(selectedDate)
  
  // Disable if filled and not today (matching legacy logic)
  return isFilled && !isCurrentToday
}

const validateEndTime = () => {
  fieldErrors.endTime = []
  
  if (formData.startTime && formData.endTime) {
    if (formData.endTime < formData.startTime) {
      fieldErrors.endTime.push('End time cannot be before start time.')
    }
  }
}

const validateForm = (): boolean => {
  // Reset errors
  Object.keys(fieldErrors).forEach((key) => {
    fieldErrors[key as keyof typeof fieldErrors] = []
  })
  
  let isValid = true
  
  // Validate date
  if (!formData.date) {
    fieldErrors.date.push('Date is required')
    isValid = false
  } else if (isEdit.value && checkIsToday(new Date(formData.date))) {
    fieldErrors.date.push('You cannot edit for the current date.')
    isValid = false
  }
  
  // Validate location
  if (!formData.location) {
    fieldErrors.location.push('Location is required')
    isValid = false
  }
  
  // Validate for past dates
  if (isPastDate.value) {
    if (!formData.startTime) {
      fieldErrors.startTime.push('Start time is required')
      isValid = false
    }
    
    if (!formData.endTime) {
      fieldErrors.endTime.push('End time is required')
      isValid = false
    } else {
      validateEndTime()
      if (fieldErrors.endTime.length > 0) {
        isValid = false
      }
    }
    
    if (!formData.reason || formData.reason.trim() === '') {
      fieldErrors.reason.push('Please tell us why you\'re adding a past entry.')
      isValid = false
    }
  }
  
  return isValid
}

const handleSubmit = async () => {
  if (!validateForm()) {
    return
  }
  
  const currentTime = format(new Date(), 'HH:mm')
  let time = currentTime
  let endTime: string | undefined = undefined
  
  const auditEntries = []
  
  if (isPastDate.value) {
    // For past dates
    time = formData.startTime
    endTime = formData.endTime
    
    auditEntries.push({
      action: 'Time In',
      time,
      reason: formData.reason
    })
    
    auditEntries.push({
      action: 'Time Out',
      time: endTime
    })
  } else {
    // For today
    auditEntries.push({
      action: 'Time In',
      time,
      comment: formData.note ? `${formData.note} (${formData.location})` : '',
      reason: formData.reason
    })
  }
  
  const submitData = {
    id: isEdit.value ? props.editData?.id : 0,
    date: formData.date,
    startTime: time,
    endTime: endTime || null,
    location: formData.location,
    note: formData.note || null,
    reason: formData.reason || null,
    audit: auditEntries
  }
  
  emit('submit', submitData)
}

const handleClose = () => {
  // Reset form
  Object.assign(formData, {
    date: '',
    startTime: '',
    endTime: '',
    location: '',
    note: '',
    reason: ''
  })
  
  // Clear errors
  Object.keys(fieldErrors).forEach((key) => {
    fieldErrors[key as keyof typeof fieldErrors] = []
  })
  
  emit('update:modelValue', false)
}

// Watchers
watch(() => props.modelValue, (isOpen) => {
  if (isOpen && props.editData) {
    nextTick(() => {
      formData.date = props.editData.date
      formData.startTime = props.editData.startTime
      formData.endTime = props.editData.endTime
      formData.location = props.editData.location
      formData.note = props.editData.notes || ''
      formData.reason = props.editData.reason || ''
    })
  } else if (isOpen && !props.editData) {
    // New entry
    nextTick(() => {
      formData.date = today.value
      formData.startTime = ''
      formData.endTime = ''
      formData.location = ''
      formData.note = ''
      formData.reason = ''
    })
  }
})
</script>

<style scoped>
.dialog-header {
  background: #ffffff;
}

/* Legacy MUI dialog styling */
:deep(.v-text-field) {
  margin-bottom: 0;
}

:deep(.v-select) {
  margin-bottom: 0;
}

:deep(.v-field__input) {
  font-size: 0.875rem;
}

:deep(.v-label) {
  font-size: 0.875rem;
}

:deep(.v-btn) {
  text-transform: uppercase;
  letter-spacing: 0.02857em;
  font-weight: 500;
}

.dark-color {
  color: #273A50;
}
</style>
